name:                xmod-inlining
version:             0.1.0.0
github:              "0xd34df00d/xmod-inlining"
license:             BSD-3-Clause
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2024 Georg Rudoy"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0xd34df00d/xmod-inlining#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- template-haskell
- vector

default-extensions:
- ImportQualifiedPost
- RecordWildCards
- Strict

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2

library:
  source-dirs: src

executables:
  xmod-inlining-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    dependencies:
    - xmod-inlining
